export { default as relaunch } from './relaunch'
export { default as getThemeColor } from './getThemeColor'
export { default as setWindowGlass } from './setWindowGlass'
export { default as registerProtocol } from './protocol'
export { default as conf } from './conf'
export { default as main_emitter } from './main_emitter'

export * from './is'
export * from './trpc'
export * from './time'
export * from './safeStorage'
export * from './const'
export * from './electron'
export * from './fs'
export * from './path'
export * from './task'
