packages:
      - 'packages/*'
catalog:
      'ai': ^6.0.0-beta.138
      'ahooks': ^3.9.6
      'bun': 1.3.4
      'bun-types': 1.3.4
      'dayjs': ^1.11.19
      'es-toolkit': 1.42.0
      'fs-extra': ^11.3.2
      'i18next': 25.7.2
      'react-i18next': 16.4.0
      'react': 19.2.1
      'react-dom': 19.2.1
      '@rslib/core': 0.18.3
      'shiki': 3.19.0
      'zod': 4.1.13
      '@types/react': 19.2.7
      '@types/react-dom': 19.2.3
      '@types/node': 24.10.2
onlyBuiltDependencies:
      - electron
      - bun
      - simple-git-hooks
