export default () => {
	return [
		{ name: 'grep', desc: 'Search file contents by text pattern' },
		{ name: 'tree', desc: 'Display directory tree structure' },
		{ name: 'rg', desc: 'Fast recursive text search' },
		{ name: 'fd', desc: 'Fast file discovery by name' },
		{ name: 'cat', desc: 'Print file contents' },
		{ name: 'head', desc: 'Print the first lines of files' },
		{ name: 'tail', desc: 'Print the last lines of files' },
		{ name: 'lsof', desc: 'List open files and sockets' },
		{ name: 'patch', desc: 'Apply unified diff patches' },
		{ name: 'diff', desc: 'Compare file differences' },
		{ name: 'sed', desc: 'Stream text transformation' },
		{ name: 'awk', desc: 'Pattern-based text processing' },
		{ name: 'sg', desc: 'Run ast-grep structural search' },
		{ name: 'jq', desc: 'Process JSON input and output' },
		{ name: 'git', desc: 'Inspect or modify git repository state' },
		{ name: 'rm', desc: 'Remove files or directories' },
		{ name: 'mv', desc: 'Move or rename files' },
		{ name: 'cp', desc: 'Copy files or directories' },
		{ name: 'chmod', desc: 'Change file mode bits' },
		{ name: 'chown', desc: 'Change file ownership' },
		{ name: 'dd', desc: 'Copy raw data between devices or files' },
		{ name: 'mkfs', desc: 'Create a filesystem on a device' },
		{ name: 'fdisk', desc: 'Manage disk partition tables' },
		{ name: 'kill', desc: 'Send signals to a process id' },
		{ name: 'pkill', desc: 'Send signals by process name pattern' },
		{ name: 'killall', desc: 'Terminate processes by name' },
		{ name: 'curl', desc: 'Transfer data from or to URLs' },
		{ name: 'wget', desc: 'Download files from the network' },
		{ name: 'ssh', desc: 'Open a remote secure shell session' },
		{ name: 'sudo', desc: 'Execute commands with elevated privileges' }
	]
}
