export const is_dev = process.env.NODE_ENV === 'development'
export const is_prod = process.env.NODE_ENV === 'production'
export const base_url = process.env.NEXT_PUBLIC_BASE_URL ?? ''
export const base_url_files = process.env.NEXT_PUBLIC_BASE_URL_FILES ?? '/images'
export const base_url_files_website = process.env.NEXT_PUBLIC_BASE_URL_FILES_WEBSITE ?? '/images'
export const google_analytics_id = process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID ?? 'G-BMS61G0JZT'
export const is_server = typeof window === 'undefined'
